In [14]:
import pandas as pd

In [15]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [16]:
df = pd.read_csv("/home/moritus-peters/Documents/Analysis-for-a-cost-of-2-cup-recommendation-by-USDA-for-a-household/data/fruits.csv")

In [17]:
df

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Apples,Fresh,1.8541,per pound,0.90,0.2425,pounds,0.4996
1,"Apples, applesauce",Canned,1.1705,per pound,1.00,0.5401,pounds,0.6323
2,"Apples, ready-to-drink",Juice,0.8699,per pint,1.00,8.0000,fluid ounces,0.4349
3,"Apples, frozen concentrate",Juice,0.6086,per pint,1.00,8.0000,fluid ounces,0.3043
4,Apricots,Fresh,3.6162,per pound,0.93,0.3638,pounds,1.4145
5,"Apricots, packed in juice",Canned,1.8645,per pound,1.00,0.5401,pounds,1.0071
6,"Apricots, packed in syrup or water",Canned,2.2362,per pound,0.65,0.4409,pounds,1.5169
7,Apricots,Dried,7.6611,per pound,1.00,0.1433,pounds,1.0978
8,Bananas,Fresh,0.5971,per pound,0.64,0.3307,pounds,0.3085
9,"Berries, mixed",Frozen,4.2673,per pound,1.00,0.3307,pounds,1.4112
10,Blackberries,Fresh,6.7483,per pound,0.96,0.3197,pounds,2.2471
11,Blackberries,Frozen,4.8277,per pound,1.00,0.3307,pounds,1.5965
12,Blueberries,Fresh,4.1575,per pound,0.95,0.3197,pounds,1.3990
13,Blueberries,Frozen,3.8210,per pound,1.00,0.3307,pounds,1.2636
14,Cantaloupe,Fresh,0.7523,per pound,0.51,0.3748,pounds,0.5528
15,Cherries,Fresh,4.6632,per pound,0.92,0.3417,pounds,1.7321
16,"Cherries, packed in syrup or water",Canned,5.2418,per pound,0.65,0.4409,pounds,3.5558
17,Clementines,Fresh,1.5811,per pound,0.77,0.4630,pounds,0.9507
18,Cranberries,Dried,5.0828,per pound,1.00,0.1232,pounds,0.6260
19,Dates,Dried,5.7499,per pound,1.00,0.1653,pounds,0.9507
20,Figs,Dried,7.3233,per pound,0.96,0.1653,pounds,1.2613
21,"Fruit cocktail, packed in juice",Canned,2.3940,per pound,1.00,0.5401,pounds,1.2931
22,"Fruit cocktail, packed in syrup or water",Canned,2.0996,per pound,0.65,0.4409,pounds,1.4242
23,Grapefruit,Fresh,1.4444,per pound,0.49,0.4630,pounds,1.3647
24,"Grapefruit, ready-to-drink",Juice,1.1935,per pint,1.00,8.0000,fluid ounces,0.5968
25,Grapes,Fresh,2.0363,per pound,0.96,0.3307,pounds,0.7014
26,Grapes (raisins),Dried,3.9936,per pound,1.00,0.1653,pounds,0.6603
27,"Grapes, ready-to-drink",Juice,1.0509,per pint,1.00,8.0000,fluid ounces,0.5255
28,"Grapes, frozen concentrate",Juice,0.7524,per pint,1.00,8.0000,fluid ounces,0.3762
29,Honeydew,Fresh,1.1589,per pound,0.46,0.3748,pounds,0.9442
30,Kiwi,Fresh,2.6064,per pound,0.76,0.3858,pounds,1.3231
31,Mangoes,Fresh,1.4698,per pound,0.71,0.3638,pounds,0.7531
32,Mangoes,Dried,10.3035,per pound,1.00,0.1253,pounds,1.2906
33,Nectarines,Fresh,2.3721,per pound,0.91,0.3197,pounds,0.8333
34,Oranges,Fresh,1.4624,per pound,0.68,0.4079,pounds,0.8771
35,"Oranges, ready-to-drink",Juice,1.0572,per pint,1.00,8.0000,fluid ounces,0.5286
36,"Oranges, frozen concentrate",Juice,0.7338,per pint,1.00,8.0000,fluid ounces,0.3669
37,Papaya,Fresh,1.3375,per pound,0.62,0.3086,pounds,0.6658
38,Papaya,Dried,7.4854,per pound,1.00,0.1543,pounds,1.1552
39,Peaches,Fresh,2.1785,per pound,0.96,0.3417,pounds,0.7755
40,"Peaches, packed in juice",Canned,2.2503,per pound,1.00,0.5401,pounds,1.2155
41,"Peaches, packed in syrup or water",Canned,2.0102,per pound,0.65,0.4409,pounds,1.3636
42,Peaches,Frozen,3.6058,per pound,1.00,0.3307,pounds,1.1924
43,Pears,Fresh,1.8472,per pound,0.90,0.3638,pounds,0.7466
44,"Pears, packed in juice",Canned,2.1400,per pound,1.00,0.5401,pounds,1.1559
45,"Pears, packed in syrup or water",Canned,2.0920,per pound,0.65,0.4409,pounds,1.4191
46,Pineapple,Fresh,0.6170,per pound,0.51,0.3638,pounds,0.4401
47,"Pineapple, packed in juice",Canned,1.6509,per pound,1.00,0.5401,pounds,0.8917
48,"Pineapple, packed in syrup or water",Canned,1.7771,per pound,0.65,0.4409,pounds,1.2055
49,Pineapple,Dried,7.0133,per pound,1.00,0.1543,pounds,1.0823
50,"Pineapple, ready-to-drink",Juice,1.2243,per pint,1.00,8.0000,fluid ounces,0.6122
51,"Pineapple, frozen concentrate",Juice,0.7256,per pint,1.00,8.0000,fluid ounces,0.3628
52,Plum,Fresh,2.5259,per pound,0.94,0.3638,pounds,0.9775
53,Plum (prunes),Dried,6.3293,per pound,1.00,0.1874,pounds,1.1861
54,"Plum (prune), ready-to-drink",Juice,1.6988,per pint,1.00,8.0000,fluid ounces,0.8494
55,Pomegranate,Fresh,2.4672,per pound,0.56,0.3417,pounds,1.5055
56,"Pomegranate, ready-to-drink",Juice,3.2788,per pint,1.00,8.0000,fluid ounces,1.6394
57,Raspberries,Fresh,7.7338,per pound,0.96,0.3197,pounds,2.5753
58,Raspberries,Frozen,6.1590,per pound,1.00,0.3307,pounds,2.0368
59,Strawberries,Fresh,2.9682,per pound,0.94,0.3197,pounds,1.0094
60,Strawberries,Frozen,3.3421,per pound,1.00,0.3307,pounds,1.1052
61,Watermelon,Fresh,0.3820,per pound,0.52,0.3307,pounds,0.2429

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fruit               62 non-null     object
 1   Form                62 non-null     object
 2   RetailPrice         62 non-null     float64
 3   RetailPriceUnit     62 non-null     object
 4   Yield               62 non-null     float64
 5   CupEquivalentSize   62 non-null     float64
 6   CupEquivalentUnit   62 non-null     object
 7   CupEquivalentPrice  62 non-null     float64
dtypes: float64(4), object(4)
memory usage: 4.0+ KB

In [19]:
df.shape

(62, 8)

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
RetailPrice,62.0,2.994571,2.269393,0.3820,1.364225,2.15925,4.116525,10.3035
Yield,62.0,0.876129,0.174979,0.4600,0.722500,0.98000,1.000000,1.0000
CupEquivalentSize,62.0,1.704984,2.949262,0.1232,0.322450,0.36380,0.540100,8.0000
CupEquivalentPrice,62.0,1.065056,0.578325,0.2429,0.639300,1.00825,1.353475,3.5558

In [21]:
df.isnull().sum()*100/len(df)

Fruit                 0.0
Form                  0.0
RetailPrice           0.0
RetailPriceUnit       0.0
Yield                 0.0
CupEquivalentSize     0.0
CupEquivalentUnit     0.0
CupEquivalentPrice    0.0
dtype: float64

In [22]:
df1 = pd.read_csv("/home/moritus-peters/Documents/Analysis-for-a-cost-of-2-cup-recommendation-by-USDA-for-a-household/data/vegetables.csv")

In [23]:
df

,Fruit,Form,RetailPrice,RetailPriceUnit,Yield,CupEquivalentSize,CupEquivalentUnit,CupEquivalentPrice
0,Apples,Fresh,1.8541,per pound,0.90,0.2425,pounds,0.4996
1,"Apples, applesauce",Canned,1.1705,per pound,1.00,0.5401,pounds,0.6323
2,"Apples, ready-to-drink",Juice,0.8699,per pint,1.00,8.0000,fluid ounces,0.4349
3,"Apples, frozen concentrate",Juice,0.6086,per pint,1.00,8.0000,fluid ounces,0.3043
4,Apricots,Fresh,3.6162,per pound,0.93,0.3638,pounds,1.4145
5,"Apricots, packed in juice",Canned,1.8645,per pound,1.00,0.5401,pounds,1.0071
6,"Apricots, packed in syrup or water",Canned,2.2362,per pound,0.65,0.4409,pounds,1.5169
7,Apricots,Dried,7.6611,per pound,1.00,0.1433,pounds,1.0978
8,Bananas,Fresh,0.5971,per pound,0.64,0.3307,pounds,0.3085
9,"Berries, mixed",Frozen,4.2673,per pound,1.00,0.3307,pounds,1.4112
10,Blackberries,Fresh,6.7483,per pound,0.96,0.3197,pounds,2.2471
11,Blackberries,Frozen,4.8277,per pound,1.00,0.3307,pounds,1.5965
12,Blueberries,Fresh,4.1575,per pound,0.95,0.3197,pounds,1.3990
13,Blueberries,Frozen,3.8210,per pound,1.00,0.3307,pounds,1.2636
14,Cantaloupe,Fresh,0.7523,per pound,0.51,0.3748,pounds,0.5528
15,Cherries,Fresh,4.6632,per pound,0.92,0.3417,pounds,1.7321
16,"Cherries, packed in syrup or water",Canned,5.2418,per pound,0.65,0.4409,pounds,3.5558
17,Clementines,Fresh,1.5811,per pound,0.77,0.4630,pounds,0.9507
18,Cranberries,Dried,5.0828,per pound,1.00,0.1232,pounds,0.6260
19,Dates,Dried,5.7499,per pound,1.00,0.1653,pounds,0.9507
20,Figs,Dried,7.3233,per pound,0.96,0.1653,pounds,1.2613
21,"Fruit cocktail, packed in juice",Canned,2.3940,per pound,1.00,0.5401,pounds,1.2931
22,"Fruit cocktail, packed in syrup or water",Canned,2.0996,per pound,0.65,0.4409,pounds,1.4242
23,Grapefruit,Fresh,1.4444,per pound,0.49,0.4630,pounds,1.3647
24,"Grapefruit, ready-to-drink",Juice,1.1935,per pint,1.00,8.0000,fluid ounces,0.5968
25,Grapes,Fresh,2.0363,per pound,0.96,0.3307,pounds,0.7014
26,Grapes (raisins),Dried,3.9936,per pound,1.00,0.1653,pounds,0.6603
27,"Grapes, ready-to-drink",Juice,1.0509,per pint,1.00,8.0000,fluid ounces,0.5255
28,"Grapes, frozen concentrate",Juice,0.7524,per pint,1.00,8.0000,fluid ounces,0.3762
29,Honeydew,Fresh,1.1589,per pound,0.46,0.3748,pounds,0.9442
30,Kiwi,Fresh,2.6064,per pound,0.76,0.3858,pounds,1.3231
31,Mangoes,Fresh,1.4698,per pound,0.71,0.3638,pounds,0.7531
32,Mangoes,Dried,10.3035,per pound,1.00,0.1253,pounds,1.2906
33,Nectarines,Fresh,2.3721,per pound,0.91,0.3197,pounds,0.8333
34,Oranges,Fresh,1.4624,per pound,0.68,0.4079,pounds,0.8771
35,"Oranges, ready-to-drink",Juice,1.0572,per pint,1.00,8.0000,fluid ounces,0.5286
36,"Oranges, frozen concentrate",Juice,0.7338,per pint,1.00,8.0000,fluid ounces,0.3669
37,Papaya,Fresh,1.3375,per pound,0.62,0.3086,pounds,0.6658
38,Papaya,Dried,7.4854,per pound,1.00,0.1543,pounds,1.1552
39,Peaches,Fresh,2.1785,per pound,0.96,0.3417,pounds,0.7755
40,"Peaches, packed in juice",Canned,2.2503,per pound,1.00,0.5401,pounds,1.2155
41,"Peaches, packed in syrup or water",Canned,2.0102,per pound,0.65,0.4409,pounds,1.3636
42,Peaches,Frozen,3.6058,per pound,1.00,0.3307,pounds,1.1924
43,Pears,Fresh,1.8472,per pound,0.90,0.3638,pounds,0.7466
44,"Pears, packed in juice",Canned,2.1400,per pound,1.00,0.5401,pounds,1.1559
45,"Pears, packed in syrup or water",Canned,2.0920,per pound,0.65,0.4409,pounds,1.4191
46,Pineapple,Fresh,0.6170,per pound,0.51,0.3638,pounds,0.4401
47,"Pineapple, packed in juice",Canned,1.6509,per pound,1.00,0.5401,pounds,0.8917
48,"Pineapple, packed in syrup or water",Canned,1.7771,per pound,0.65,0.4409,pounds,1.2055
49,Pineapple,Dried,7.0133,per pound,1.00,0.1543,pounds,1.0823
50,"Pineapple, ready-to-drink",Juice,1.2243,per pint,1.00,8.0000,fluid ounces,0.6122
51,"Pineapple, frozen concentrate",Juice,0.7256,per pint,1.00,8.0000,fluid ounces,0.3628
52,Plum,Fresh,2.5259,per pound,0.94,0.3638,pounds,0.9775
53,Plum (prunes),Dried,6.3293,per pound,1.00,0.1874,pounds,1.1861
54,"Plum (prune), ready-to-drink",Juice,1.6988,per pint,1.00,8.0000,fluid ounces,0.8494
55,Pomegranate,Fresh,2.4672,per pound,0.56,0.3417,pounds,1.5055
56,"Pomegranate, ready-to-drink",Juice,3.2788,per pint,1.00,8.0000,fluid ounces,1.6394
57,Raspberries,Fresh,7.7338,per pound,0.96,0.3197,pounds,2.5753
58,Raspberries,Frozen,6.1590,per pound,1.00,0.3307,pounds,2.0368
59,Strawberries,Fresh,2.9682,per pound,0.94,0.3197,pounds,1.0094
60,Strawberries,Frozen,3.3421,per pound,1.00,0.3307,pounds,1.1052
61,Watermelon,Fresh,0.3820,per pound,0.52,0.3307,pounds,0.2429

In [24]:
df.shape

(62, 8)